Class {
	#name : #FamixPythonAnnotationType,
	#superclass : #FamixPythonEntity,
	#traits : 'FamixTAnnotationType',
	#classTraits : 'FamixTAnnotationType classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonAnnotationType class >> annotation [

	<FMClass: #AnnotationType super: #FamixPythonEntity>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
