Class {
	#name : #FamixPythonAnnotationType,
	#superclass : #FamixPythonNamedEntity,
	#traits : 'FamixTAnnotationType',
	#classTraits : 'FamixTAnnotationType classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonAnnotationType class >> annotation [

	<FMClass: #AnnotationType super: #FamixPythonNamedEntity>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
